### ISSUE TITLE
Pequeno problema (Pesquisa)

### ISSUE THREAD

**Issue by alexandrecoder** [rodolfogoulart/aletheia-core-model#3]
Olá Rodolfo, gostaria de informar logo de cara que não sou um programador de fato, apenas um curioso, mas notei um problema que pode estar influenciando no uso do aplicativo para alguns usuários, que pode ter influenciado na avaliação abaixo:

![image](https://github.com/user-attachments/assets/afb3dd0b-47f0-4907-ba8b-784b51c4ba54)

Basicamente o que acontece é que ao iniciar o aplicativo, a parte do texto da bíblia não carrega automaticamente:

![image](https://github.com/user-attachments/assets/b6740d5b-cccd-457d-943b-56afa99bb944)

Sendo necessário escolher um capítulo para aparecer o texto:

![image](https://github.com/user-attachments/assets/73732d5f-3579-49e2-9f98-b0713ffc6444)

Dessa forma, acredito que se na inicialização fosse carregado automaticamente o último capítulo ou Gn. 1 no caso de ser a primeira abertura, poderia evitar problemas para usuários mais leigos que podem achar que o aplicativo está "quebrado".

Deus te abençoe!

**Comment by rodolfogoulart** [comment]
Obrigado @alexandrecoder 
Eu postei um comentário para ele entrar em contato comigo.

Realmente, para alguns usuário que utilizavam a versão antiga **1.0.11**, houve uma mudança no layout bem grande, e talvez tenha um pouco de confusão para uso inicial. 
Para incluir a pesquisa e padronizar melhor a UI eu fiz bastante modificações, e de fato facilitaria já ter o texto pesquisado ao entrar no app, obrigado pela sugestão, estou implementando para a próxima versão.

Espero que ele entre em contato, porque uma das modificações novas teve que baixar uma nova base de dados, talvez ele possa ter algum problema com isso, neste caso teria outra maneira de solucionar, porque a desinstalação não apaga a base de dados antiga, ficando resquícios da instalação antiga.


Desde já agradeço por contribuir.
Se tiver algum feedback do app, bug, ideia, dados que ajudariam em estudos, agradeço em compartilhar.

**Comment by alexandrecoder** [comment]
Obrigado por responder!

Em seg., 5 de ago. de 2024 12:18, Rodolfo Goulart ***@***.***>
escreveu:
