### ISSUE TITLE
[Bug] - 

### ISSUE THREAD

**Issue by Teresa5519** [rodolfogoulart/aletheia-core-model#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rodolfogoulart** [comment]
Olá @Teresa5519 
Teve algum problema que queria reportar?

Hello @Teresa5519 
There is a bug that you want to report?
