### ISSUE TITLE
erro no verso bíblico

### ISSUE THREAD

**Issue by rafacvlcnt** [rodolfogoulart/aletheia-core-model#5]
olá . romanos 8:20 versão NVI está escrito "inutilidade", quando na verdade é "futilidade"

**Comment by rodolfogoulart** [comment]
Olá @rafacvlcnt 

Dependendo da versão da NVI, algumas trazem o verso com a palavra **"inutilidade"** já outras trazem **"futilidade"**. Acredito que isto seja por revisão da versão. Porém o significado do trecho não altera.

>Significados: 
>  * Futilidade: "**coisa sem valor**, pequena; **insignificância**, ninharia."
>  * Inutilidade: "ausência, **falta de utilidade**, de serventia."

Sites com a NVI que trazem na Versão  a palavra **"inutilidade"**
https://www.biblegateway.com/passage/?search=Romanos%208%2CRomans%208&version=NVI-PT;NIV
https://www.bible.com/pt/bible/129/ROM.8.NVI
https://pesquisa.biblia.com.br/pt-BR/NVI/rm/8
https://www.biblica.com/america-latina/biblia/biblia-online/nvi-pt/romanos/8/nvi/
https://www.biblestudytools.com/nvip/romanos/8.html

Site com a NVI que trazem na Versão a palavra **"fulidade"**
https://www.bibliaonline.com.br/nvi/rm/8


Mas obrigado por relatar, acredito que tenha mais diferenças assim por conta da revisão da versão.
**_Obrigado por contribuir ao projeto._**
